---
title: "Money and Politics"
author: "Christine, Nybria, Yuri"
date: "March 21, 2018"
output:
  html_document:
    code_folding: hide
--- 


## Loading the data
```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggthemes)
wordcountaddin::text_stats("mp2.Rmd")
```

## Initial clean up of the data 
```{r, message=FALSE, warning=FALSE, echo=TRUE}
contributions1 <- merge(candidates, contributions, by = "cand_id") # merged the candidate dataframe and contribution dataframe by the cand_id to see the name of the candidate

house_elections1 <- rename(house_elections, cand_id = fec_id) # renamed the row 

cont_winner <- contributions1 %>%
  inner_join(house_elections1, by = "cand_id") 


new_cont <- contributions1 %>%
  select(cand_id, cand_name, cand_party_affiliation,  cand_election_yr, cand_office_state , name, transaction_amt) # there are a lot of contributions to the same representative. 


contributions1 %>% group_by(cand_party_affiliation) %>% summarize(num_type = n()) %>% arrange(desc(num_type)) %>% head(4)

cont_winner %>%
  select(cand_id, cand_name, cand_party_affiliation, transaction_amt, ge_winner) %>%
  filter(transaction_amt > 0 ) %>% #remove negative transactions
  group_by(cand_name)

cont_winner %>%
  group_by(cand_party_affiliation) %>%
  summarise( nrow = n()) %>%
  arrange(desc(nrow)) %>%
  head (5) # finding the top 5 parties with the highest number of memebers in the election


# This function will be used to filter out transaction amounts and wins for each polical party 
party <- function(name_arg) {
  cont_winner %>%
    filter(cand_party_affiliation == name_arg) %>%
    filter(ge_winner == "W") %>%
    select(transaction_amt, ge_winner) %>%
    group_by(transaction_amt, ge_winner) %>%
    summarise(trans = sum(transaction_amt), win = n()) %>%
    arrange(desc(transaction_amt))
}

# This function will be used to filter out transaction amounts and losses for each polical party 
party2 <- function(name_arg) {
  cont_winner %>%
    filter(cand_party_affiliation == name_arg) %>%
    filter(ge_winner == "N") %>%
    group_by(transaction_amt, ge_winner) %>%
    summarise(trans = sum(transaction_amt), win = n()) %>%
    arrange(desc(transaction_amt))
}  

# analyzing each of of the 5 parties and their tranaction amounts 
affiliation <- c("DEM", "REP", "DFL", "UNK", "OTH")
 lapply(affiliation, FUN = party2)
  

cont_winner2 <- cont_winner %>%
  filter(cand_party_affiliation %in% c("REP", "DEM", "DFL", "UNK", "OTH"))

```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
#This will change the ge_winner factors around so that win will appear as the first bar with lose following. 
cont_winner2$ge_winner <- factor(cont_winner2$ge_winner, levels = c("W", "N"))

levels(cont_winner2$ge_winner)
```

```{r, message=FALSE, warning=FALSE, echo=TRUE}
positions <- c("DEM","REP","DFL","UNK","OTH") #This will change the positon of the factors on the plot 

party_plot_bar <- ggplot(cont_winner2, aes(x = cand_party_affiliation, y = transaction_amt, fill = ge_winner)) +
  geom_bar(position = "dodge", stat = "identity") + 
  labs( x = "Party Affiliation", y = "Transaction Amount (millions)") + 
  scale_fill_discrete(name = "Election Results", labels = c("Win", "Lose")) +
  scale_x_discrete(limits = positions) +
  scale_y_continuous(limits = c(0, 2500000)
, breaks = seq(0, 2500000, 500000), expand = c(0,0), labels = c("0M","0.5M","1M","1.5M","2M","2.5M")) + 
  labs(title = "Does transaction amount affect win rate?", subtitle = "Exploring the relationship between contributions and election results") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme_economist_white() + scale_color_economist()

party_plot_bar
```


